=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::MenuItemsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MenuItemsApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::MenuItemsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MenuItemsApi' do
    it 'should create an instance of MenuItemsApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::MenuItemsApi)
    end
  end

  # unit tests for create_menu_item
  # Create a Menu Item
  # Creates a Menu Item
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreateMenuItemParams] :create_menu_item_params 
  # @return [Resource]
  describe 'create_menu_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_menu_item
  # Delete a Menu Item
  # Deletes a Menu Item
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_menu_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for menu_items_list
  # Return a list of Menu Items
  # Returns a list of Menu Items
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_name_eq 
  # @return [ResourcesList]
  describe 'menu_items_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reposition_menu_item
  # Reposition a Menu Item
  # Reposition a Menu Item
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [MenuItemReposition] :menu_item_reposition 
  # @return [Resource]
  describe 'reposition_menu_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_menu_item
  # Return a Menu Item
  # Returns a Menu Item
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_menu_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_menu_item
  # Update a Menu Item
  # Updates a Menu Item
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdateMenuItemParams] :update_menu_item_params 
  # @return [Resource]
  describe 'update_menu_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
