=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::PromotionRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PromotionRulesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::PromotionRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PromotionRulesApi' do
    it 'should create an instance of PromotionRulesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::PromotionRulesApi)
    end
  end

  # unit tests for create_promotion_rule
  # Create a Promotion Rule
  # Creates a Promotion Rule
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreatePromotionRuleParams] :create_promotion_rule_params 
  # @return [Resource]
  describe 'create_promotion_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_promotion_rule
  # Delete a Promotion Rule
  # Deletes a Promotion Rule
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_promotion_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for promotion_rules_list
  # Return a list of Promotion Rules
  # Returns a list of Promotion Rules
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_type_eq 
  # @return [ResourcesList]
  describe 'promotion_rules_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_promotion_rule
  # Return a Promotion Rule
  # Returns a Promotion Rule
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_promotion_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_promotion_rule
  # Update a Promotion Rule
  # Updates a Promotion Rule
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdatePromotionRuleParams] :update_promotion_rule_params 
  # @return [Resource]
  describe 'update_promotion_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
