=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::RolesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RolesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::RolesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RolesApi' do
    it 'should create an instance of RolesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::RolesApi)
    end
  end

  # unit tests for create_role
  # Create a Role
  # Creates a Role
  # @param [Hash] opts the optional parameters
  # @option opts [CreateRoleParams] :create_role_params 
  # @return [Resource]
  describe 'create_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_role
  # Delete a Role
  # Deletes a Role
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for roles_list
  # Return a list of Roles
  # Returns a list of Roles
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :filter_name_eq 
  # @return [ResourcesList]
  describe 'roles_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_role
  # Return a Role
  # Returns a Role
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Resource]
  describe 'show_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_role
  # Update a Role
  # Updates a Role
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateRoleParams] :update_role_params 
  # @return [Resource]
  describe 'update_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
