=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::ShippingMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ShippingMethodsApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::ShippingMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShippingMethodsApi' do
    it 'should create an instance of ShippingMethodsApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::ShippingMethodsApi)
    end
  end

  # unit tests for create_shipping_method
  # Create a Shipping Method
  # Creates a Shipping Method
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreateShippingMethodParams] :create_shipping_method_params 
  # @return [Resource]
  describe 'create_shipping_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_shipping_method
  # Delete a Shipping Method
  # Deletes a Shipping Method
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_shipping_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for shipping_methods_list
  # Return a list of Shipping Methods
  # Returns a list of Shipping Methods
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_name 
  # @option opts [String] :filter_title_cont 
  # @return [ResourcesList]
  describe 'shipping_methods_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_shipping_method
  # Return a Shipping Method
  # Returns a Shipping Method
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_shipping_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_shipping_method
  # Update a Shipping Method
  # Updates a Shipping Method
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdateShippingMethodParams] :update_shipping_method_params 
  # @return [Resource]
  describe 'update_shipping_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
