=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::StatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::StatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatesApi' do
    it 'should create an instance of StatesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::StatesApi)
    end
  end

  # unit tests for show_state
  # Returns a State
  # Returns a State
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Resource]
  describe 'show_state test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for states_list
  # Returns a list of States
  # Returns a list of States
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_country_id_eq 
  # @return [ResourcesList]
  describe 'states_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
