=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::StoreCreditCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StoreCreditCategoriesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::StoreCreditCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StoreCreditCategoriesApi' do
    it 'should create an instance of StoreCreditCategoriesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::StoreCreditCategoriesApi)
    end
  end

  # unit tests for create_store_credit_category
  # Create a Store Credit Category
  # Creates a Store Credit Category
  # @param [Hash] opts the optional parameters
  # @option opts [CreateStoreCreditCategoryParams] :create_store_credit_category_params 
  # @return [Resource]
  describe 'create_store_credit_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_store_credit_category
  # Delete a Store Credit Category
  # Deletes a Store Credit Category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_store_credit_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_store_credit_category
  # Return a Store Credit Category
  # Returns a Store Credit Category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Resource]
  describe 'show_store_credit_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for store_credit_categories_list
  # Return a list of Store Credit Categories
  # Returns a list of Store Credit Categories
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :filter_name_eq 
  # @return [ResourcesList]
  describe 'store_credit_categories_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_store_credit_category
  # Update a Store Credit Category
  # Updates a Store Credit Category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateStoreCreditCategoryParams] :update_store_credit_category_params 
  # @return [Resource]
  describe 'update_store_credit_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
