=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::TaxRatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxRatesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::TaxRatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxRatesApi' do
    it 'should create an instance of TaxRatesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::TaxRatesApi)
    end
  end

  # unit tests for create_tax_rate
  # Create a Tax Rate
  # Creates a Tax Rate
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreateTaxRateParams] :create_tax_rate_params 
  # @return [Resource]
  describe 'create_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tax_rate
  # Delete a Tax Rate
  # Deletes a Tax Rate
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_tax_rate
  # Return a Tax Rate
  # Returns a Tax Rate
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tax_rates_list
  # Return a list of Tax Rates
  # Returns a list of Tax Rates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_zone_id_eq 
  # @option opts [String] :filter_amount_gt 
  # @option opts [String] :filter_tax_category_id_eq 
  # @return [ResourcesList]
  describe 'tax_rates_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tax_rate
  # Update a Tax Rate
  # Updates a Tax Rate
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdateTaxRateParams] :update_tax_rate_params 
  # @return [Resource]
  describe 'update_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
