=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::TaxonsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxonsApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::TaxonsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxonsApi' do
    it 'should create an instance of TaxonsApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::TaxonsApi)
    end
  end

  # unit tests for create_taxon
  # Create a Taxon
  # Creates a Taxon
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreateTaxonParams] :create_taxon_params 
  # @return [Resource]
  describe 'create_taxon test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_taxon
  # Delete a Taxon
  # Deletes a Taxon
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_taxon test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reposition_taxon
  # Reposition a Taxon
  # Reposition a Taxon
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [TaxonReposition] :taxon_reposition 
  # @return [Resource]
  describe 'reposition_taxon test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_taxon
  # Return a Taxon
  # Returns a Taxon
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_taxon test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for taxons_list
  # Return a list of Taxons
  # Returns a list of Taxons
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_taxonomy_id_eq 
  # @option opts [String] :filter_name_cont 
  # @return [ResourcesList]
  describe 'taxons_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_taxon
  # Update a Taxon
  # Updates a Taxon
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdateTaxonParams] :update_taxon_params 
  # @return [Resource]
  describe 'update_taxon test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
