=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::TaxonomiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxonomiesApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::TaxonomiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxonomiesApi' do
    it 'should create an instance of TaxonomiesApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::TaxonomiesApi)
    end
  end

  # unit tests for create_taxonomy
  # Create a Taxonomy
  # Creates a Taxonomy
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [CreateTaxonomyParams] :create_taxonomy_params 
  # @return [Resource]
  describe 'create_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_taxonomy
  # Delete a Taxonomy
  # Deletes a Taxonomy
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_taxonomy
  # Return a Taxonomy
  # Returns a Taxonomy
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @return [Resource]
  describe 'show_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for taxonomies_list
  # Return a list of Taxonomies
  # Returns a list of Taxonomies
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_name_eq 
  # @return [ResourcesList]
  describe 'taxonomies_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_taxonomy
  # Update a Taxonomy
  # Updates a Taxonomy
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [UpdateTaxonomyParams] :update_taxonomy_params 
  # @return [Resource]
  describe 'update_taxonomy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
