=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SpreeClient::WebhookEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookEventsApi' do
  before do
    # run before each test
    @api_instance = SpreeClient::WebhookEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookEventsApi' do
    it 'should create an instance of WebhookEventsApi' do
      expect(@api_instance).to be_instance_of(SpreeClient::WebhookEventsApi)
    end
  end

  # unit tests for webhook_events_list
  # Return a list of Webhook Events
  # Returns a list of Webhook Events
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :include Select which associated resources you would like to fetch, see: &lt;a href&#x3D;\&quot;https://jsonapi.org/format/#fetching-includes\&quot;&gt;https://jsonapi.org/format/#fetching-includes&lt;/a&gt;
  # @option opts [String] :filter_name_eq 
  # @option opts [String] :filter_request_errors_cont 
  # @option opts [String] :filter_response_code_eq 
  # @option opts [String] :filter_success_eq 
  # @option opts [String] :filter_url_cont 
  # @return [ResourcesList]
  describe 'webhook_events_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
