=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'date'
require 'time'

module SpreeClient
  class CreateImageGalleryCmsSectionParamsCmsSection
    # Give this section a name.
    attr_accessor :name

    # Set the `cms_page` ID that this section belongs to.
    attr_accessor :cms_page_id

    # Set the section type.
    attr_accessor :type

    # Pass the position that you want this section to appear in. (The list is not zero indexed, so the first item is position: `1`)
    attr_accessor :position

    # Set the resource type that image one links to.
    attr_accessor :link_type_one

    # Set the resource type that image two links to.
    attr_accessor :link_type_two

    # Set the resource type that image three links to.
    attr_accessor :link_type_three

    # Set the slug or path that image two links to.
    attr_accessor :link_one

    # Set the slug or path that image two links to.
    attr_accessor :link_two

    # Set the slug or path that image three links to.
    attr_accessor :link_three

    # Set the title used in image one.
    attr_accessor :title_one

    # Set the title used in image two.
    attr_accessor :title_two

    # Set the title used in image three.
    attr_accessor :title_three

    # This value is used by front end developers to set CSS classes for content that fits the screen edge-to-edge, or stays within the boundaries of the central container.
    attr_accessor :fit

    # This value is used by front end developers for styling the order the images appear.
    attr_accessor :layout_style

    # This value is used by front end developers for showing and hiding the label on the images.
    attr_accessor :display_labels

    # Use a `multipart/form-data` request to upload assets.
    attr_accessor :cms_section_image_one

    # Use a `multipart/form-data` request to upload assets.
    attr_accessor :cms_section_image_two

    # Use a `multipart/form-data` request to upload assets.
    attr_accessor :cms_section_image_three

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'cms_page_id' => :'cms_page_id',
        :'type' => :'type',
        :'position' => :'position',
        :'link_type_one' => :'link_type_one',
        :'link_type_two' => :'link_type_two',
        :'link_type_three' => :'link_type_three',
        :'link_one' => :'link_one',
        :'link_two' => :'link_two',
        :'link_three' => :'link_three',
        :'title_one' => :'title_one',
        :'title_two' => :'title_two',
        :'title_three' => :'title_three',
        :'fit' => :'fit',
        :'layout_style' => :'layout_style',
        :'display_labels' => :'display_labels',
        :'cms_section_image_one' => :'cms_section[image_one]',
        :'cms_section_image_two' => :'cms_section[image_two]',
        :'cms_section_image_three' => :'cms_section[image_three]'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'cms_page_id' => :'String',
        :'type' => :'String',
        :'position' => :'Integer',
        :'link_type_one' => :'String',
        :'link_type_two' => :'String',
        :'link_type_three' => :'String',
        :'link_one' => :'String',
        :'link_two' => :'String',
        :'link_three' => :'String',
        :'title_one' => :'String',
        :'title_two' => :'String',
        :'title_three' => :'String',
        :'fit' => :'String',
        :'layout_style' => :'String',
        :'display_labels' => :'String',
        :'cms_section_image_one' => :'File',
        :'cms_section_image_two' => :'File',
        :'cms_section_image_three' => :'File'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'link_one',
        :'link_two',
        :'link_three',
        :'title_one',
        :'title_two',
        :'title_three',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SpreeClient::CreateImageGalleryCmsSectionParamsCmsSection` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SpreeClient::CreateImageGalleryCmsSectionParamsCmsSection`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'cms_page_id')
        self.cms_page_id = attributes[:'cms_page_id']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'position')
        self.position = attributes[:'position']
      end

      if attributes.key?(:'link_type_one')
        self.link_type_one = attributes[:'link_type_one']
      end

      if attributes.key?(:'link_type_two')
        self.link_type_two = attributes[:'link_type_two']
      end

      if attributes.key?(:'link_type_three')
        self.link_type_three = attributes[:'link_type_three']
      end

      if attributes.key?(:'link_one')
        self.link_one = attributes[:'link_one']
      end

      if attributes.key?(:'link_two')
        self.link_two = attributes[:'link_two']
      end

      if attributes.key?(:'link_three')
        self.link_three = attributes[:'link_three']
      end

      if attributes.key?(:'title_one')
        self.title_one = attributes[:'title_one']
      end

      if attributes.key?(:'title_two')
        self.title_two = attributes[:'title_two']
      end

      if attributes.key?(:'title_three')
        self.title_three = attributes[:'title_three']
      end

      if attributes.key?(:'fit')
        self.fit = attributes[:'fit']
      end

      if attributes.key?(:'layout_style')
        self.layout_style = attributes[:'layout_style']
      end

      if attributes.key?(:'display_labels')
        self.display_labels = attributes[:'display_labels']
      end

      if attributes.key?(:'cms_section_image_one')
        self.cms_section_image_one = attributes[:'cms_section_image_one']
      end

      if attributes.key?(:'cms_section_image_two')
        self.cms_section_image_two = attributes[:'cms_section_image_two']
      end

      if attributes.key?(:'cms_section_image_three')
        self.cms_section_image_three = attributes[:'cms_section_image_three']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @cms_page_id.nil?
        invalid_properties.push('invalid value for "cms_page_id", cms_page_id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @cms_page_id.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["Spree::Cms::Sections::ImageGallery"])
      return false unless type_validator.valid?(@type)
      link_type_one_validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      return false unless link_type_one_validator.valid?(@link_type_one)
      link_type_two_validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      return false unless link_type_two_validator.valid?(@link_type_two)
      link_type_three_validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      return false unless link_type_three_validator.valid?(@link_type_three)
      fit_validator = EnumAttributeValidator.new('String', ["Screen", "Container"])
      return false unless fit_validator.valid?(@fit)
      layout_style_validator = EnumAttributeValidator.new('String', ["Default", "Reversed"])
      return false unless layout_style_validator.valid?(@layout_style)
      display_labels_validator = EnumAttributeValidator.new('String', ["Show", "Hide"])
      return false unless display_labels_validator.valid?(@display_labels)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["Spree::Cms::Sections::ImageGallery"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link_type_one Object to be assigned
    def link_type_one=(link_type_one)
      validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      unless validator.valid?(link_type_one)
        fail ArgumentError, "invalid value for \"link_type_one\", must be one of #{validator.allowable_values}."
      end
      @link_type_one = link_type_one
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link_type_two Object to be assigned
    def link_type_two=(link_type_two)
      validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      unless validator.valid?(link_type_two)
        fail ArgumentError, "invalid value for \"link_type_two\", must be one of #{validator.allowable_values}."
      end
      @link_type_two = link_type_two
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link_type_three Object to be assigned
    def link_type_three=(link_type_three)
      validator = EnumAttributeValidator.new('String', ["Spree::Taxon", "Spree::Product"])
      unless validator.valid?(link_type_three)
        fail ArgumentError, "invalid value for \"link_type_three\", must be one of #{validator.allowable_values}."
      end
      @link_type_three = link_type_three
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fit Object to be assigned
    def fit=(fit)
      validator = EnumAttributeValidator.new('String', ["Screen", "Container"])
      unless validator.valid?(fit)
        fail ArgumentError, "invalid value for \"fit\", must be one of #{validator.allowable_values}."
      end
      @fit = fit
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] layout_style Object to be assigned
    def layout_style=(layout_style)
      validator = EnumAttributeValidator.new('String', ["Default", "Reversed"])
      unless validator.valid?(layout_style)
        fail ArgumentError, "invalid value for \"layout_style\", must be one of #{validator.allowable_values}."
      end
      @layout_style = layout_style
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] display_labels Object to be assigned
    def display_labels=(display_labels)
      validator = EnumAttributeValidator.new('String', ["Show", "Hide"])
      unless validator.valid?(display_labels)
        fail ArgumentError, "invalid value for \"display_labels\", must be one of #{validator.allowable_values}."
      end
      @display_labels = display_labels
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          cms_page_id == o.cms_page_id &&
          type == o.type &&
          position == o.position &&
          link_type_one == o.link_type_one &&
          link_type_two == o.link_type_two &&
          link_type_three == o.link_type_three &&
          link_one == o.link_one &&
          link_two == o.link_two &&
          link_three == o.link_three &&
          title_one == o.title_one &&
          title_two == o.title_two &&
          title_three == o.title_three &&
          fit == o.fit &&
          layout_style == o.layout_style &&
          display_labels == o.display_labels &&
          cms_section_image_one == o.cms_section_image_one &&
          cms_section_image_two == o.cms_section_image_two &&
          cms_section_image_three == o.cms_section_image_three
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, cms_page_id, type, position, link_type_one, link_type_two, link_type_three, link_one, link_two, link_three, title_one, title_two, title_three, fit, layout_style, display_labels, cms_section_image_one, cms_section_image_two, cms_section_image_three].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = SpreeClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
