=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SpreeClient::CreateDigitalLinkParamsDigitalLink
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SpreeClient::CreateDigitalLinkParamsDigitalLink do
  let(:instance) { SpreeClient::CreateDigitalLinkParamsDigitalLink.new }

  describe 'test an instance of CreateDigitalLinkParamsDigitalLink' do
    it 'should create an instance of CreateDigitalLinkParamsDigitalLink' do
      expect(instance).to be_instance_of(SpreeClient::CreateDigitalLinkParamsDigitalLink)
    end
  end
  describe 'test attribute "access_counter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "line_item_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "digital_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
