=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SpreeClient::TaxonRepositionTaxon
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SpreeClient::TaxonRepositionTaxon do
  let(:instance) { SpreeClient::TaxonRepositionTaxon.new }

  describe 'test an instance of TaxonRepositionTaxon' do
    it 'should create an instance of TaxonRepositionTaxon' do
      expect(instance).to be_instance_of(SpreeClient::TaxonRepositionTaxon)
    end
  end
  describe 'test attribute "new_parent_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_position_idx"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
