=begin
#Platform API

#Spree Platform API

The version of the OpenAPI document: v2
Contact: we@sparksolutions.co
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SpreeClient::UpdateAdjustmentParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SpreeClient::UpdateAdjustmentParams do
  let(:instance) { SpreeClient::UpdateAdjustmentParams.new }

  describe 'test an instance of UpdateAdjustmentParams' do
    it 'should create an instance of UpdateAdjustmentParams' do
      expect(instance).to be_instance_of(SpreeClient::UpdateAdjustmentParams)
    end
  end
  describe 'test attribute "adjustment"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
